import { Platform } from 'types/promo-slider.types';
import { IPromoApp } from 'types/promo-tabs.types';

export const promoApps: IPromoApp[] = [
    {
        id: 1,
        platform: Platform.Mac,
        appName: 'Widgetter - Custom Desktop',
        title: 'Widgetter - Custom Desktop',
        subtitle: 'Widgets & wallpaper customizer',
        description:
            'Widgetter is a direct line to upscaling your desktop into a work station perfectly tailored to your needs. Huge collection of widgets and wallpapers will meet every user’s expectations. Start building a customized home screen to have all the key data points and basic functions always remain available at a glance.',
        bgImage: '/assets/bg/widgetter-bg.png',
        icon: '/assets/tab-icons/widgetter-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/widgetter/big/01.png',
            '/assets/slides/widgetter/big/02.png',
            '/assets/slides/widgetter/big/03.png',
            '/assets/slides/widgetter/big/04.png',
            '/assets/slides/widgetter/big/05.png',
            '/assets/slides/widgetter/big/06.png',
            '/assets/slides/widgetter/big/07.png',
            '/assets/slides/widgetter/big/08.png',
        ],
        smallSlides: [
            '/assets/slides/widgetter/small/01.jpg',
            '/assets/slides/widgetter/small/02.jpg',
            '/assets/slides/widgetter/small/03.jpg',
            '/assets/slides/widgetter/small/04.jpg',
            '/assets/slides/widgetter/small/05.jpg',
            '/assets/slides/widgetter/small/06.jpg',
            '/assets/slides/widgetter/small/07.jpg',
            '/assets/slides/widgetter/small/08.jpg',
        ],
    },
    {
        id: 2,
        platform: Platform.Mac,
        appName: 'Audio One: Easy Music Editing',
        title: 'Audio One: Easy Music Editing',
        subtitle: 'Sound Editor & Ringtone Maker',
        description:
            'Audio One is a functional and simple, user friendly audio tool fully adapted for Mac. In short, this is exactly what you were looking for. Audio One is suitable for beginners and experienced sound designers.',
        bgImage: '/assets/bg/audio-one-bg.png',
        icon: '/assets/tab-icons/audio-one-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/audio-one-mac/big/01.png',
            '/assets/slides/audio-one-mac/big/02.png',
            '/assets/slides/audio-one-mac/big/03.png',
            '/assets/slides/audio-one-mac/big/04.png',
            '/assets/slides/audio-one-mac/big/05.png',
        ],
        smallSlides: [
            '/assets/slides/audio-one-mac/small/01.jpg',
            '/assets/slides/audio-one-mac/small/02.jpg',
            '/assets/slides/audio-one-mac/small/03.jpg',
            '/assets/slides/audio-one-mac/small/04.jpg',
            '/assets/slides/audio-one-mac/small/05.jpg',
        ],
    },
    {
        id: 3,
        platform: Platform.Ios,
        appName: 'Audio One: Multitrack Editing',
        title: 'Audio One: Multitrack Editing',
        subtitle: 'Ringtone Maker & Music Editor',
        description:
            'Audio One is a functional and simple, user friendly audio tool fully adapted for iOS. This software is versatile and ideal for both working with podcasts, lectures, performances, and for creating the coolest ringtones and music tracks.',
        bgImage: '/assets/bg/audio-one-bg.png',
        icon: '/assets/tab-icons/audio-one-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/audio-one-ios/big/01.png',
            '/assets/slides/audio-one-ios/big/02.png',
            '/assets/slides/audio-one-ios/big/03.png',
            '/assets/slides/audio-one-ios/big/04.png',
            '/assets/slides/audio-one-ios/big/05.png',
        ],
        smallSlides: [
            '/assets/slides/audio-one-ios/small/01.jpg',
            '/assets/slides/audio-one-ios/small/02.jpg',
            '/assets/slides/audio-one-ios/small/03.jpg',
            '/assets/slides/audio-one-ios/small/04.jpg',
            '/assets/slides/audio-one-ios/small/05.jpg',
        ],
    },
    {
        id: 4,
        platform: Platform.Ios,
        appName: 'GPS Run, Walking & Ski Tracker',
        title: 'GPS Run, Walking & Ski Tracker',
        subtitle: 'My Steps & Calorie-counter App',
        description:
            'Going for a hike, cycling, swimming or running  – make GPS Sports Tracker  your companion whenever you’re on the move. The app is designed to collect and process the data about the key parameters of any training and wrap it up into concise, digestible graphs.',
        bgImage: '/assets/bg/gps-bg.png',
        icon: '/assets/tab-icons/gps-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/gps/big/01.png',
            '/assets/slides/gps/big/02.png',
            '/assets/slides/gps/big/03.png',
            '/assets/slides/gps/big/04.png',
            '/assets/slides/gps/big/05.png',
        ],
        smallSlides: [
            '/assets/slides/gps/small/01.jpg',
            '/assets/slides/gps/small/02.jpg',
            '/assets/slides/gps/small/03.jpg',
            '/assets/slides/gps/small/04.jpg',
            '/assets/slides/gps/small/05.jpg',
        ],
    },
    {
        id: 5,
        platform: Platform.Mac,
        appName: 'Alarm Clock: Wake Up & Go',
        title: 'Alarm Clock: Wake Up & Go',
        subtitle: 'Sleep Control & Timer',
        description:
            'Alarm Clock is a functional yet simple, user friendly and stylish tool fully adapted for your Mac. It will ensure a comfortable awakening at the right time.',
        bgImage: '/assets/bg/alarm-clock-bg.png',
        icon: '/assets/tab-icons/alarm-clock-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/alarm-clock/big/01.png',
            '/assets/slides/alarm-clock/big/02.png',
            '/assets/slides/alarm-clock/big/03.png',
            '/assets/slides/alarm-clock/big/04.png',
            '/assets/slides/alarm-clock/big/05.png',
        ],
        smallSlides: [
            '/assets/slides/alarm-clock/small/01.jpg',
            '/assets/slides/alarm-clock/small/02.jpg',
            '/assets/slides/alarm-clock/small/03.jpg',
            '/assets/slides/alarm-clock/small/04.jpg',
            '/assets/slides/alarm-clock/small/05.jpg',
        ],
    },
    {
        id: 6,
        platform: Platform.Mac,
        appName: 'Audio Converter - One Click',
        title: 'Audio Converter - One Click',
        subtitle: 'Convert to mp3, wav, mp4, flac',
        description:
            'Audio Converter is really a simple and handy tool for converting audio files of different formats -  mp3, mp4, wav, flac, aiff, aac, m4a and etc.',
        bgImage: '/assets/bg/audio-converter-bg.png',
        icon: '/assets/tab-icons/audio-converter-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/audio-converter/big/01.png',
            '/assets/slides/audio-converter/big/02.png',
            '/assets/slides/audio-converter/big/03.png',
            '/assets/slides/audio-converter/big/04.png',
        ],
        smallSlides: [
            '/assets/slides/audio-converter/small/01.jpg',
            '/assets/slides/audio-converter/small/02.jpg',
            '/assets/slides/audio-converter/small/03.jpg',
            '/assets/slides/audio-converter/small/04.jpg',
        ],
    },
    {
        id: 7,
        platform: Platform.Mac,
        appName: 'Voice Memos - Audio Recorder',
        title: 'Voice Memos - Audio Recorder',
        subtitle: 'Speech To Text Notes: Notepad',
        description:
            'Immerse yourself in the world of your own emotions! Record important things with your voice and get audio and text in one place. Merge records and collect memories.',
        bgImage: '/assets/bg/voice-memos-bg.png',
        icon: '/assets/tab-icons/voice-memos-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/voice-memos-mac/big/01.png',
            '/assets/slides/voice-memos-mac/big/02.png',
            '/assets/slides/voice-memos-mac/big/03.png',
            '/assets/slides/voice-memos-mac/big/04.png',
        ],
        smallSlides: [
            '/assets/slides/voice-memos-mac/small/01.jpg',
            '/assets/slides/voice-memos-mac/small/02.jpg',
            '/assets/slides/voice-memos-mac/small/03.jpg',
            '/assets/slides/voice-memos-mac/small/04.jpg',
        ],
    },
    {
        id: 8,
        platform: Platform.Ios,
        appName: 'Voice Memos - Dictate Notes',
        title: 'Voice Memos - Dictate Notes',
        subtitle: 'Live transcribe speech to text',
        description:
            'We’ve created this app to help you create memories. Add your text, photos, audio, set the password or vice versa share your memos with your friends. It’s up to you!',
        bgImage: '/assets/bg/voice-memos-bg.png',
        icon: '/assets/tab-icons/voice-memos-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/voice-memos-ios/big/01.png',
            '/assets/slides/voice-memos-ios/big/02.png',
            '/assets/slides/voice-memos-ios/big/03.png',
            '/assets/slides/voice-memos-ios/big/04.png',
        ],
        smallSlides: [
            '/assets/slides/voice-memos-ios/small/01.jpg',
            '/assets/slides/voice-memos-ios/small/02.jpg',
            '/assets/slides/voice-memos-ios/small/03.jpg',
            '/assets/slides/voice-memos-ios/small/04.jpg',
        ],
    },
    {
        id: 9,
        platform: Platform.Ios,
        appName: 'Books Reader - Pocket Library',
        title: 'Books Reader - Pocket Library',
        subtitle: 'Reading tracker & open ebooks',
        description:
            'Books Reader is a pocket library and intuitive tool for a perfect reading experience. Without extra fluff or complexity, it takes care of all the basic needs: managing your ebook collections, getting the text on the screen and letting you interact with it as you go at your prime reading.',
        bgImage: '/assets/bg/books-reader-bg.png',
        icon: '/assets/tab-icons/books-reader-icon.png',
        storeIcon: '',
        bigSlides: [
            '/assets/slides/books-reader/big/01.png',
            '/assets/slides/books-reader/big/02.png',
            '/assets/slides/books-reader/big/03.png',
            '/assets/slides/books-reader/big/04.png',
        ],
        smallSlides: [
            '/assets/slides/books-reader/small/01.jpg',
            '/assets/slides/books-reader/small/02.jpg',
            '/assets/slides/books-reader/small/03.jpg',
            '/assets/slides/books-reader/small/04.jpg',
        ],
    },
];
